package com.zgp.dao;

import com.zgp.cartitem.povo.cartitemPovo;
import com.zgp.domain.CartItem;
import com.zgp.domain.CartItemExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Tue Jun 27 12:37:17 CST 2017
     */
    int countByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Tue Jun 27 12:37:17 CST 2017
     */
    int deleteByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Tue Jun 27 12:37:17 CST 2017
     */
    int deleteByPrimaryKey(String cartitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Tue Jun 27 12:37:17 CST 2017
     */
    int insert(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Tue Jun 27 12:37:17 CST 2017
     */
    int insertSelective(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Tue Jun 27 12:37:17 CST 2017
     */
    List<CartItem> selectByExample(CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Tue Jun 27 12:37:17 CST 2017
     */
    CartItem selectByPrimaryKey(String cartitemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Tue Jun 27 12:37:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") CartItem record, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Tue Jun 27 12:37:17 CST 2017
     */
    int updateByExample(@Param("record") CartItem record, @Param("example") CartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Tue Jun 27 12:37:17 CST 2017
     */
    int updateByPrimaryKeySelective(CartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cartitem
     *
     * @mbggenerated Tue Jun 27 12:37:17 CST 2017
     */
    int updateByPrimaryKey(CartItem record);

	List<cartitemPovo> selectcartitemByUid(String uid);

	/*void delete2(Map<String, Object> map);*/

	List<cartitemPovo> jiesuan(Map<String, Object> map);

	cartitemPovo selectCartItemPoVoByCartitemid(String cartitemid);
}