package com.zgp.dao;

import com.zgp.domain.Dingdan;
import com.zgp.domain.DingdanExample;
import com.zgp.order.PoVo.dingdanPoVo;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DingdanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    int countByExample(DingdanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    int deleteByExample(DingdanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    int insert(Dingdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    int insertSelective(Dingdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    List<Dingdan> selectByExample(DingdanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    Dingdan selectByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") Dingdan record, @Param("example") DingdanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    int updateByExample(@Param("record") Dingdan record, @Param("example") DingdanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    int updateByPrimaryKeySelective(Dingdan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dingdan
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    int updateByPrimaryKey(Dingdan record);

	List<dingdanPoVo> selectDingdanByUid(String uid);

	dingdanPoVo selectbyoid(String oid);

	void updateStatus(Map<String, Object> map);
}