package com.zgp.domain;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cid
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cname
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.pid
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.miaoshu
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    private String miaoshu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.shunxu
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    private Integer shunxu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cid
     *
     * @return the value of category.cid
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cid
     *
     * @param cid the value for category.cid
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cname
     *
     * @return the value of category.cname
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cname
     *
     * @param cname the value for category.cname
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.pid
     *
     * @return the value of category.pid
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.pid
     *
     * @param pid the value for category.pid
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.miaoshu
     *
     * @return the value of category.miaoshu
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    public String getMiaoshu() {
        return miaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.miaoshu
     *
     * @param miaoshu the value for category.miaoshu
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    public void setMiaoshu(String miaoshu) {
        this.miaoshu = miaoshu == null ? null : miaoshu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.shunxu
     *
     * @return the value of category.shunxu
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    public Integer getShunxu() {
        return shunxu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.shunxu
     *
     * @param shunxu the value for category.shunxu
     *
     * @mbggenerated Tue Jun 27 12:37:16 CST 2017
     */
    public void setShunxu(Integer shunxu) {
        this.shunxu = shunxu;
    }
}